server:
  port: 7080
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:certificado.p12

spring:
  application:
    name: gateway

zuul:
  sensitive-headers: Coockie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    auth:
      url: http://localhost:5000
    produto:
      url: http://localhost:5001
    meli:
      url: http://localhost:5002

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7081/eureka/