server:
  port: 7080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://dibros-store-discovery.up.railway.app/eureka/