server:
  port: 7080
  ssl:
    enabled: true
    key-store: classpath:dibros.ddns.net.jks
    key-store-password: '031290'

spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

zuul:
  sensitive-headers: Coockie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7081/eureka/
