server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  sensitive-headers: Coockie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    auth:
      url: http://dibros.ddns.net:8083
    produto:
      url: http://dibros.ddns.net:8086
    meli:
      url: http://dibros.ddns.net:8085

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://dibros-eureka.up.railway.app/eureka/