server:
  port: 7080
  ssl:
    enabled: false
    key-store: classpath:dibros.ddns.net.jks
    key-store-password: '031290'

spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/dibros?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  config:
    login-url: /auth/login
    type: "signed"

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7081/eureka/

