server:
  port: 7080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:dibros.p12
    key-store-password: 'dibros'

spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/dibros?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  config:
    login-url: /auth/login
    type: "signed"

zuul:
  host:
    socket-timeout-millis: 300000
    connect-timeout-millis: 100000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7081/eureka/
