server:
  port: 7080
  ssl:
    enabled: true
    key-store: classpath:dibros.jks
    key-store-type: JKS
    key-store-password: dibros

spring:
  application:
    name: gateway

zuul:
  sensitive-headers: Coockie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  routes:
#    auth:
#      url: http://dibros.ddns.net:5000
#    produto:
#      url: http://dibros.ddns.net:5001
#    meli:
#      url: http://dibros.ddns.net:5002

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7081/eureka/