server:
  port: 8080
spring:
  application:
    name: gateway

zuul:
  sensitive-headers: Coockie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    auth:
      url: https://dibros-auth.up.railway.app
    produtos:
      url: https://dibros-produto.up.railway.app
    meli:
      url: https://dibros-meli.up.railway.app

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://dibros-discovery.up.railway.app/eureka/