server:
  port: 7080

eureka:
  client:
    service-url:
      defaultZone: https://dibros-discovery.up.railway.app/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000